easy_admin:
    site_name: 'Panel Admin'
    design:
        brand_color: 'rgb(255, 153, 0)'
        color_scheme: 'light'
        form_theme: 'vertical'
        #c1 : rgb(255, 153, 0)
        #c2 : rgb(255, 204, 51)
        #c3 : rgb(255, 102, 0)
        #c4 : rgb(255, 255, 209)
        templates:
            layout: '@AdminBundle/layout.html.twig'
        assets:
            css:
                - 'bundles/admin/css/admin.css'
        menu:
            - { label: 'Accueil', route: 'produit_index' }
            - { label: 'Configuration' }
            - { entity: 'Caracteristique', icon: 'tag' }
            - { entity: 'Categorie', icon: 'sitemap' }
            - { label: 'Contenu' }
            - { entity: 'Utilisateur', icon: 'user' }
            - { entity: 'Produit', icon: 'shopping-cart' }
            - { entity: 'Commande', icon: 'credit-card' }
            - { label: 'Monitoring' }
            - { label: '30 derniers jours', route: 'analytics_index', icon: 'area-chart' }      
    list:
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Caracteristique:
            class: AppBundle\Entity\Caracteristique
            list:
                fields:
                    - nom
                    - format
            form:
                fields:
                    - nom
                    - format
        Categorie:
            class: AppBundle\Entity\Categorie
            list:
                fields:
                    - titre
                    - description
            form:
                fields:
                    - titre
                    - description
        Commande:
            class: AppBundle\Entity\Commande
            list:
                fields:
                    - {property: 'date', type: 'datetime'}
                    - prix
                    - statut
                    - utilisateur
            form:
                fields:
                    - utilisateur
                    - {property: 'date', type: 'datetime'}
                    - { property: 'commandeP', label: 'Produits', type: 'collection', type_options: { entry_type: 'AdminBundle\Form\CommandePType',entry_options:  {label: false}, by_reference: false } }  
                    - prix
                    - statut
                    
        Produit:
            class: AppBundle\Entity\Produit
            controller: AdminBundle\Controller\ProduitController
            list:
                fields:
                    - titre
                    - { property: 'imageUrl', type: 'image', label: 'Image'}
                    - prix
                    - quantite
                    - { property: 'updatedAt', type: 'datetime', label: 'Modifié'}
            show:
                fields:
                    - titre
                    - description
                    - { property: 'imageUrl', type: 'image', label: 'Image'}
                    - prix
                    - quantite
                    - { property: 'updatedAt', type: 'datetime', label: 'Modifié'}
            form:
                fields:
                    - titre
                    - { property: 'description', type: 'textarea'}
                    - prix
                    - quantite
                    - { property: 'categorieP', label: 'Catégorie', type: 'collection', type_options: {entry_type: 'AdminBundle\Form\CategoriePType',entry_options:  {label: false}, by_reference: false }  }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'caracteristiqueP', label: 'Caracteristique', type: 'collection', type_options: { entry_type: 'AdminBundle\Form\CaracteristiquePType',entry_options:  {label: false}, by_reference: false } }  
        Utilisateur:
            class: UserBundle\Entity\Utilisateur
            list:
                fields:
                    - username
                    - email
                    - enabled
                    - {property: 'lastlogin', type: 'datetime', label: 'Connexion'}
            form:
                fields:
                    - username
                    - email
                    - enabled
           