easy_admin:
    site_name: 'Panel Admin'
    design:
        brand_color: 'darkgreen'
        color_scheme: 'dark'
        form_theme: 'horizontal'
        #templates:
            #layout: '@AdminBundle/layout.html.twig'
        menu:
            - { label: 'Accueil', url: '/test_technique/web/app_dev.php' }
            - { label: 'Configuration' }
            - { entity: 'Caracteristique', icon: 'tag' }
            - { entity: 'Categorie', icon: 'sitemap' }
            - { label: 'Contenu' }
            - { entity: 'Utilisateur', icon: 'user' }
            - { entity: 'Produit', icon: 'shopping-cart' }
            - { entity: 'Commande', icon: 'credit-card' }
            - { label: 'Monitoring' }
            
    list:
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Caracteristique:
            class: AppBundle\Entity\Caracteristique
            list:
                fields:
                    - nom
                    - format
            form:
                fields:
                    - nom
                    - format
        Categorie:
            class: AppBundle\Entity\Categorie
            list:
                fields:
                    - titre
                    - description
            form:
                fields:
                    - titre
                    - description
        Commande:
            class: AppBundle\Entity\Commande
            list:
                fields:
                    - {property: 'date', type: 'datetime'}
                    - prix
                    - statut
                    - utilisateur
            form:
                fields:
                    - utilisateur
                    - {property: 'date', type: 'datetime'}
                    - { property: 'commandeP', label: 'Produits', type: 'collection', type_options: { entry_type: 'AdminBundle\Form\CommandePType',entry_options:  {label: false}, by_reference: false } }  
                    - prix
                    - statut
                    
        Produit:
            class: AppBundle\Entity\Produit
            controller: AdminBundle\Controller\ProduitController
            list:
                fields:
                    - titre
                    - { property: 'imageUrl', type: 'image', label: 'Image'}
                    - prix
                    - quantite
                    - { property: 'updatedAt', type: 'datetime', label: 'Modifié'}
            show:
                fields:
                    - titre
                    - description
                    - { property: 'imageUrl', type: 'image', label: 'Image'}
                    - prix
                    - quantite
                    - { property: 'updatedAt', type: 'datetime', label: 'Modifié'}
            form:
                fields:
                    - titre
                    - { property: 'description', type: 'textarea'}
                    - prix
                    - quantite
                    - { property: 'categorieP', label: 'Catégorie', type: 'entity', type_options: { class: 'AppBundle\Entity\Categorie', multiple: false, attr: { data-widget: 'select2' } }  }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'caracteristiqueP', label: 'Caracteristique', type: 'collection', type_options: { entry_type: 'AdminBundle\Form\CaracteristiquePType',entry_options:  {label: false}, by_reference: false } }  
        Utilisateur:
            class: UserBundle\Entity\Utilisateur
            list:
                fields:
                    - username
                    - email
                    - enabled
                    - {property: 'lastlogin', type: 'datetime', label: 'Connexion'}
            form:
                fields:
                    - username
                    - email
                    - enabled
            
        
        #{ property: 'tag', type: 'entity', type_options: { class: 'MyEntity', multiple: true, attr: { data-widget: 'select2' } }  }
        
#        News:
#            class: gt3\SiteBundle\Entity\News
#            list:
#                fields: [titre,categorie,date,utilisateur,suppression]
#            form:
#                fields: [titre,categorie,date,utilisateur,{property: 'suite', type: 'ckeditor' }]
#        Utilisateurs:
#            class: gt3\SiteBundle\Entity\Utilisateurs
#            list:
#                fields: [nom,mail,level,categorie,equipe]
#            form:
#                fields: [nom,description,mail,level,categorie,equipe]
#        Categorie:
#            class: gt3\SiteBundle\Entity\Categorie
#            list:
#                fields: [id,nom,{property: 'uri', label: 'Lien'},initiales,visibilite,idforum]
#            form:
#                fields: [nom,{property: 'uri', label: 'Lien'},initiales,visibilite,idforum]
#        Rubrique:
#            class: gt3\SiteBundle\Entity\Rubrique
#            list:
#                fields: [nom,{property: 'uri', label: 'Lien'},{property: 'level', label: 'visibilité'},rang,parent,suppression]
#            form:
#                fields: [nom,{property: 'uri', label: 'Lien'},level,rang,parent,suppression]
#        Pages: 
#            class: gt3\SiteBundle\Entity\Pages
#        Module:
#            class: gt3\SiteBundle\Entity\Module
#        Equipe:
#            class: gt3\SiteBundle\Entity\Equipe
#        RangEquipe:
#            class: gt3\SiteBundle\Entity\RangEquipe
#        Matchs:
#            class: gt3\SiteBundle\Entity\Matchs
#        Webtv:
#            class: gt3\SiteBundle\Entity\Webtv
#        EmissionWebtv:
#            class: gt3\SiteBundle\Entity\EmissionWebtv
#        EquipeUtilisateurs:
#            class: gt3\SiteBundle\Entity\EquipeUtilisateurs
        
           