<?php

namespace AppBundle\Repository;

/**
 * Caracteristique_ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Caracteristique_ProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
