<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository {

    public function findByCategorie($categorie) {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select('p')
                        ->from('AppBundle:Produit', 'p')
                        ->leftJoin('p.categorieP', 'cp')
                        ->where('cp.produit = p.id')
                        ->andWhere('cp.categorie = :id')
                        ->setParameter('id', $categorie)->getQuery();

        return $query->getResult();
    }

}
