# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.root: "%kernel.root_dir%/Resources/analytics/data"

services:
    admin.analytics.helper:
        class:        AdminBundle\Helper\AnalyticsHelper
        arguments: ["@google_analytics_api.api",%google_analytics_view_id%,%app.root%]
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
